## depends on: https://marketplace.visualstudio.com/items?itemName=gittools.gittools

name: $(date:yyyyMMdd)$(rev:.r)-$(Build.SourceBranchName)-$(GitVersion.SemVer)

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  contentVersion: $(GitVersion.AssemblySemVer)
  parameters.semVer.value: $(GitVersion.AssemblySemVer)

steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

#GitHubRelease
- task: PowerShell@2
  displayName: 'Get latest SHA commmit from repo'
  inputs:
    targetType: 'inline'
    script: |
      $commits = Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/cpoDesign/APITestingRunner/commits"
      $sha = $commits[0].sha
      Write-Host "##vso[task.setvariable variable=sha;]$sha"

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'


- task: gitversion/execute@0
  displayName: 'Calculate SemVer'
  
- script: echo current version is $(GitVersion.SemVer)
  displayName: 'Display calculated version'
  
# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'github.com_cpoDesign'
#     repositoryName: 'cpoDesign/APITestingRunner'
#     action: 'create'
#     target: '$(sha)'
#     tagSource: 'userSpecifiedTag'
#     tag: '$(GitVersion.SemVer)'
#     title: 'v$(GitVersion.SemVer)'
#     assets: '$(Build.ArtifactStagingDirectory)\release\*.exe'
#     addChangeLog: true