# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# GitHubRelease
# - task: PowerShell@2
#   displayName: 'Get latest SHA commmit from repo'
#   inputs:
#     targetType: 'inline'
#     script: |
#       $commits = Invoke-RestMethod -Method GET -Uri "https://api.github.com/repos/Account/repo/commits"
#       $sha = $commits[0].sha
#       Write-Host "##vso[task.setvariable variable=sha;]$sha"

# - task: GitHubRelease@1
#   inputs:
#     gitHubConnection: 'example_github'
#     repositoryName: 'cpoDesign/APITestingRunner'
#     action: 'create'
#     target: '$(sha)'
#     tagSource: 'userSpecifiedTag'
#     tag: '$(tag)'
#     title: 'v$(tag)'
#     assets: '$(Build.ArtifactStagingDirectory)\release\*.exe'
#     addChangeLog: false